[package]
name = "actix-session-test"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies]
actix-files = "0.2.1"
actix-web = "2.0.0"
actix-rt = "1.1.1"
actix-service = "1.0.5"
actix-session = "0.3.0"
